### ISSUE TITLE
Repository name is not a plugin name

### ISSUE THREAD

**Issue by jjatria** [badner/lab_to_praat#10]
When using `git clone`, the default name of the target directory is taken from the name of the repository, such that 

    cd ~
    git clone https://github.com/badner/lab_to_praat.git

will result in the creation of the directory `~/lab_to_praat`.

Praat plugins are detected as such by

1. Being in the Praat preferences directory
2. In a directory whose name matches `/^plugin_/`

The scripts as they are right now assume "htklabel" for the name of this plugin (in order to be able to specify paths, etc, so that name is really just temporary). If you think that that name is acceptable, would you consider renaming this repository to `plugin_htklabel`, so that cloning it from the preferences directory results in the correct directory being created?

If `htklabel` is not acceptable, I'd recommend choosing a name that is, and then renaming the repository to match. For the record, `plugin_lab_to_praat` should also be valid.

**Comment by CShulby** [comment]
done
