### ISSUE TITLE
Save as HTK Label File error

### ISSUE THREAD

**Issue by CShulby** [badner/lab_to_praat#18]
When I tried to save the modified .lab file to the Desktop I got the following error

Command "Get start time of interval:" not available for current selection.
Script line 3436 not performed or completed:
« this = Get start time of interval: tier, i »
Please change something in the command window “Run script: Save as HTK label file...”, or click Cancel in that window.

**Comment by CShulby** [comment]
it does create the output tables but doesn't remove them.  something is going wrong at the start of the script where it should find the starting point.  Any ideas?

**Comment by jjatria** [comment]
Odd. This works in my installation.

What version of Praat are you running?

Also, do the tests pass on your machine? What happens if you run `cpran test htklabel`?

**Comment by CShulby** [comment]
I get this error when I run: cpran test htklabel

There should be a space after the three dots.
Script line 28 not performed or completed:
« Add menu command: "Objects", "Praat", "Select one type...",
"selection", 2, "scripts/select_one_type.praat" »
Script “/home/badner/.praat-dir/plugin_selection/setup.praat” not completed.
Praat: plugin “/home/badner/.praat-dir/plugin_selection/setup.praat”
contains an error.

2017-04-28 12:35 GMT-03:00 José Joaquín Atria <notifications@github.com>:

**Comment by jjatria** [comment]
Interesting.

Again: what version of Praat are you running?

**Comment by CShulby** [comment]
I have 5.3.16-1ubuntu2 installed on my system.  It does not find the plugin.

I also have 6.0.28 as a compiled exe file which does find the plugins but
gives me the save error

2017-04-28 12:54 GMT-03:00 Christopher Shulby <chrisshulby@gmail.com>:

**Comment by CShulby** [comment]
ok I copied praat to the correct location by using sudo cp ./praat
/usr/bin/.

and I was able to get the output from cpran test htklabel which is:

t/query_mlf.t ........
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 7/17 subtests
t/read_context.t .....
Dubious, test returned 255 (wstat 65280, 0xff00)
All 4 subtests passed
t/read_mlf.t ......... ok
t/read_no_context.t ..
Dubious, test returned 255 (wstat 65280, 0xff00)
All 4 subtests passed
t/write.t ............
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run

Test Summary Report
-------------------
t/query_mlf.t      (Wstat: 65280 Tests: 10 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 17 tests but ran 10.
t/read_context.t   (Wstat: 65280 Tests: 4 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/read_no_context.t (Wstat: 65280 Tests: 4 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/write.t          (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=5, Tests=24,  0 wallclock secs ( 0.02 usr  0.03 sys +  0.14 cusr
0.05 csys =  0.24 CPU)
Result: FAIL

2017-04-28 13:09 GMT-03:00 Christopher Shulby <chrisshulby@gmail.com>:

**Comment by jjatria** [comment]
This is very useful. I hadn't noticed that I had accidentally introduced some unnecessary requirements in some of the plugins used by htklabel. I've fixed this on my machine, and now I can get htklabel to pass all tests in versions 6.0.00+. I tested 5.4.22 (and it failed), but I haven't tested anything older than that.

I've been chasing this for a bit, but the errors you are finding are odd because they mean that the test did not run at all.

What happens if you run the test manually? Try running
```bash
cd ~/.praat-dir/plugin_htklabel
praat --run --ansi t/read_context.t
```

Also, could you give me the output of `cpran --version`?

**Comment by CShulby** [comment]
it seems that I had 6.0.19 on my machine, I deleted everything and downloaded praat from the git repo.  I know have 6.0.28 running fine and it does save the lab file (with some issue but I will open this in a seperate issue)

**Comment by CShulby** [comment]
I will run the test.  May be different since I updated my version now.

**Comment by CShulby** [comment]
badner@badner:~$ cd ~/.praat-dir/plugin_htklabel
badner@badner:~/.praat-dir/plugin_htklabel$ praat --run --ansi t/read_context.t
ok 1 - Script generates TextGrid without Sound
ok 2 - Script does not read Sound
ok 3 - Same number of tiers
ok 4 - Tier 1 is interval tier
#   Testing 3 intervals
ok 5 - Interval label 1
ok 6 - Interval start 1
ok 7 - Interval end 1
ok 8 - Interval label 2
ok 9 - Interval start 2
ok 10 - Interval end 2
ok 11 - Interval label 3
ok 12 - Interval start 3
ok 13 - Interval end 3
ok 14 - Script generates TextGrid with Sound
ok 15 - Script reads Sound
ok 16 - TextGrid from Sound has same duration
ok 17 - Same number of tiers
ok 18 - Tier 1 is interval tier
#   Testing 5 intervals
#   No equivalent interval in reference data!
ok 19 - Interval label 1
ok 20 - Interval start 1
ok 21 - Interval end 1
ok 22 - Interval label 2
ok 23 - Interval start 2
ok 24 - Interval end 2
ok 25 - Interval label 3
ok 26 - Interval start 3
ok 27 - Interval end 3
#   No equivalent interval in reference data!
ok 28 - Removed all local objects
1..28

**Comment by CShulby** [comment]
badner@badner:~/.praat-dir/plugin_htklabel$ cpran --version
cpran (CPrAN) version 0.0406 (/usr/local/bin/cpran)
Using Praat version 6.0.28 (/usr/bin/praat)

**Comment by jjatria** [comment]
Hmm, that's odd. So the tests run and pass, but when they are executed with the client they fail... That means the problem is with the client, and not the plugin.

I'll push a new version of the client with a minor fix (which I thought was unrelated), to see if that fixed this as well. That might work because, like I said, the plugin passes all the tests on my machine with all versions 6.0.00 and up.

I'll let you know when you can upgrade.
