### ISSUE TITLE
lab file does not save the comments or contexts

### ISSUE THREAD

**Issue by CShulby** [badner/lab_to_praat#20]
Original file:
// This is an example
// of a .lab file
000206250 001761250 yy^yy-#p+nn=an/P1:yy/P2:yy/P3:yy
001761250 002516250 yy^#p-nn+an=wn/P1:-1/P2:+0/P3:-2
002516250 003210625 #p^nn-an+wn=pp/P1:+0/P2:+1/P3:-1
003210625 004150624 nn^an-wn+pp=oh/P1:+1/P2:+2/P3:+0
004150624 004726875 an^wn-pp+oh=dz/P1:-1/P2:+0/P3:-3
004726875 006096875 wn^pp-oh+dz=ic/P1:+0/P2:+1/P3:-2
006096875 006826875 pp^oh-dz+ic=aa/P1:+1/P2:+2/P3:-1
006826875 007104375 oh^dz-ic+aa=vv/P1:+2/P2:+3/P3:+0
007104375 007401250 dz^ic-aa+vv=ee/P1:-2/P2:+0/P3:-3
007401250 007928750 ic^aa-vv+ee=rf/P1:-1/P2:+1/P3:-2
007928750 008865625 aa^vv-ee+rf=tt/P1:+0/P2:+2/P3:-1
008865625 009228750 vv^ee-rf+tt=rd/P1:+1/P2:+3/P3:+0
009228750 010173750 ee^rf-tt+rd=eh/P1:-2/P2:+0/P3:-6
010173750 010648125 rf^tt-rd+eh=gg/P1:-1/P2:+1/P3:-5
010648125 012147501 tt^rd-eh+gg=uw/P1:+0/P2:+2/P3:-4
012147501 012839375 rd^eh-gg+uw=ac/P1:+1/P2:+3/P3:-3
012839375 013133125 eh^gg-uw+ac=zz/P1:+2/P2:+4/P3:-2
013133125 013871250 gg^uw-ac+zz=nn/P1:+3/P2:+5/P3:-1
013871250 014529375 uw^ac-zz+nn=ac/P1:+4/P2:+6/P3:+0
014529375 015194376 ac^zz-nn+ac=gg/P1:yy/P2:+0/P3:-1
015194376 016180625 zz^nn-ac+gg=eh/P1:yy/P2:+1/P3:+0
016180625 016940624 nn^ac-gg+eh=rx/P1:-1/P2:+0/P3:-3
016940624 018078124 ac^gg-eh+rx=ac/P1:+0/P2:+1/P3:-2
018078124 019224376 gg^eh-rx+ac=kk/P1:+1/P2:+2/P3:-1
019224376 019870624 eh^rx-ac+kk=on/P1:+2/P2:+3/P3:+0
019870624 021035626 rx^ac-kk+on=tt/P1:-1/P2:+0/P3:-4
021035626 022470000 ac^kk-on+tt=rd/P1:+0/P2:+1/P3:-3
022470000 023106250 kk^on-tt+rd=ac/P1:+1/P2:+2/P3:-2
023106250 023483750 on^tt-rd+ac=ac/P1:+2/P2:+3/P3:-1
023483750 023690624 tt^rd-ac+ac=mm/P1:+3/P2:+4/P3:+0
023690624 023953750 rd^ac-ac+mm=aa/P1:yy/P2:+0/P3:+0
023953750 024462500 ac^ac-mm+aa=ll/P1:-3/P2:+0/P3:-6
024462500 025359376 ac^mm-aa+ll=aa/P1:-2/P2:+1/P3:-5
025359376 025976874 mm^aa-ll+aa=rr/P1:-1/P2:+2/P3:-4
025976874 027414374 aa^ll-aa+rr=ij/P1:+0/P2:+3/P3:-3
027414374 027978750 ll^aa-rr+ij=ac/P1:+1/P2:+4/P3:-2
027978750 028521874 aa^rr-ij+ac=#p/P1:+2/P2:+5/P3:-1
028521874 029427500 rr^ij-ac+#p=yy/P1:+3/P2:+6/P3:+0
029427500 031077500 ij^ac-#p+yy=yy/P1:yy/P2:yy/P3:yy

saved file:
000206250 001761250 #p
001761250 002516250 nn
002516250 003210624 an
003210624 004150624 wn
004150624 004726875 pp
004726875 006096875 oh
006096875 006826875 dz
006826875 007104375 ic
007104375 007401250 aa
007401250 007928750 vv
007928750 008865625 ee
008865625 009228750 rf
009228750 010173750 tt
010173750 010648125 rd
010648125 012147501 eh
012147501 012839375 gg
012839375 013133125 uw
013133125 013871250 ac
013871250 014529375 zz
014529375 015194376 nn
015194376 016180625 ac
016180625 016940624 gg
016940624 018078124 eh
018078124 019224376 rx
019224376 019870624 ac
019870624 021035626 kk
021035626 022470000 on
022470000 023106250 tt
023106250 023483750 rd
023483750 023690623 ac
023690623 023953750 ac
023953750 024462500 mm
024462500 025359376 aa
025359376 025976874 ll
025976874 027414374 aa
027414374 027978750 rr
027978750 028521874 ij
028521874 029427500 ac
029427500 031077499 #p

**Comment by CShulby** [comment]
this was generated using the discard context option

**Comment by CShulby** [comment]
when left unselected it generates:

000206250 001761250 yy^yy-#p+nn=an/P1:yy/P2:yy/P3:yy
001761250 002516250 yy^#p-nn+an=wn/P1:-1/P2:+0/P3:-2
002516250 003210624 #p^nn-an+wn=pp/P1:+0/P2:+1/P3:-1
003210624 004150624 nn^an-wn+pp=oh/P1:+1/P2:+2/P3:+0
004150624 004726875 an^wn-pp+oh=dz/P1:-1/P2:+0/P3:-3
004726875 006096875 wn^pp-oh+dz=ic/P1:+0/P2:+1/P3:-2
006096875 006826875 pp^oh-dz+ic=aa/P1:+1/P2:+2/P3:-1
006826875 007104375 oh^dz-ic+aa=vv/P1:+2/P2:+3/P3:+0
007104375 007401250 dz^ic-aa+vv=ee/P1:-2/P2:+0/P3:-3
007401250 007928750 ic^aa-vv+ee=rf/P1:-1/P2:+1/P3:-2
007928750 008865625 aa^vv-ee+rf=tt/P1:+0/P2:+2/P3:-1
008865625 009228750 vv^ee-rf+tt=rd/P1:+1/P2:+3/P3:+0
009228750 010173750 ee^rf-tt+rd=eh/P1:-2/P2:+0/P3:-6
010173750 010648125 rf^tt-rd+eh=gg/P1:-1/P2:+1/P3:-5
010648125 012147501 tt^rd-eh+gg=uw/P1:+0/P2:+2/P3:-4
012147501 012839375 rd^eh-gg+uw=ac/P1:+1/P2:+3/P3:-3
012839375 013133125 eh^gg-uw+ac=zz/P1:+2/P2:+4/P3:-2
013133125 013871250 gg^uw-ac+zz=nn/P1:+3/P2:+5/P3:-1
013871250 014529375 uw^ac-zz+nn=ac/P1:+4/P2:+6/P3:+0
014529375 015194376 ac^zz-nn+ac=gg/P1:yy/P2:+0/P3:-1
015194376 016180625 zz^nn-ac+gg=eh/P1:yy/P2:+1/P3:+0
016180625 016940624 nn^ac-gg+eh=rx/P1:-1/P2:+0/P3:-3
016940624 018078124 ac^gg-eh+rx=ac/P1:+0/P2:+1/P3:-2
018078124 019224376 gg^eh-rx+ac=kk/P1:+1/P2:+2/P3:-1
019224376 019870624 eh^rx-ac+kk=on/P1:+2/P2:+3/P3:+0
019870624 021035626 rx^ac-kk+on=tt/P1:-1/P2:+0/P3:-4
021035626 022470000 ac^kk-on+tt=rd/P1:+0/P2:+1/P3:-3
022470000 023106250 kk^on-tt+rd=ac/P1:+1/P2:+2/P3:-2
023106250 023483750 on^tt-rd+ac=ac/P1:+2/P2:+3/P3:-1
023483750 023690623 tt^rd-ac+ac=mm/P1:+3/P2:+4/P3:+0
023690623 023953750 rd^ac-ac+mm=aa/P1:yy/P2:+0/P3:+0
023953750 024462500 ac^ac-mm+aa=ll/P1:-3/P2:+0/P3:-6
024462500 025359376 ac^mm-aa+ll=aa/P1:-2/P2:+1/P3:-5
025359376 025976874 mm^aa-ll+aa=rr/P1:-1/P2:+2/P3:-4
025976874 027414374 aa^ll-aa+rr=ij/P1:+0/P2:+3/P3:-3
027414374 027978750 ll^aa-rr+ij=ac/P1:+1/P2:+4/P3:-2
027978750 028521874 aa^rr-ij+ac=#p/P1:+2/P2:+5/P3:-1
028521874 029427500 rr^ij-ac+#p=yy/P1:+3/P2:+6/P3:+0
029427500 031077499 ij^ac-#p+yy=yy/P1:yy/P2:yy/P3:yy

**Comment by CShulby** [comment]
the problem here is that when viewing the aligned lab file and audio in the praat edit window, the context is not useful and very distracting, however it is needed in order to train synthetic voices in HTS.

It is important to conserve the context information and print it after the file has been edited.

**Comment by jjatria** [comment]
This is really the expected behaviour. There is no way the reader could keep the comments, because they are supposed to be ignored. There is no way to keep the comments in a way that is generalisable.

As for the context, how about this:

1. We simplify the reading script to _only_ read the labels. That is, keeping all the context. No "discard_context" option at all.
2. You read the HTS label into a TextGrid (or more, but let's keep it simple).
3. We provide a _new_ script to "remove context", which removes the context from the labels, and leaves the TextGrid without context. It stores the context in a Table, with columns for context before and after the label.
4. You do whatever you need to do on the TextGrid object.
5. We provide _another_ script that takes a TextGrid and one of these Table objects, and puts the contexts back in.

So the process would be read -> remove -> edit -> insert -> save.

This might be a bit tricky if the number of intervals changes during the editing process, but as long as we can ignore that problem for now, this I think would greatly simplify the entire process.

If we add another small script that takes a TextGrid (from the label) and a Sound object, and makes the timestamps align by stretching the TextGrid, then we could make the "read" script go back to having a single parameter.

Your request is pretty specific, so I wouldn't bundle it with the plugin. But having those steps isolated, writing what you want would be very simple indeed.

**Comment by CShulby** [comment]
Ok. I think that pipeline is good and similar to my original code. The main
thing is that those who use the plugin really just want to use praat to
edit their lab files and do not want them changed (otherwise they would
just use a textgrid). It should be noted that I only have 3 features
here(p1, p2, p3). Some people will have 40 or more.

I agree that the number of intervals should not change. This would be very
rare because it would make more sense for an hts user to fix their
transcription when the lab file is generated than to do so in praat because
their transcription error would still exist in the future.

We can warn people of this behavior.

Maybe just set this as an option for HTS users and the other would be htk
oriented.

As for the comments. What I did in the first version of my script was to
save the comment lines in the header first, then I processed the rest of
the file and in the end glued them back together. This could be an option.

Am 28.04.2017 7:59 nachm. schrieb "José Joaquín Atria" <
notifications@github.com>:

**Comment by jjatria** [comment]
> As for the comments. What I did in the first version of my script was to save the comment lines in the header first, then I processed the rest of the file and in the end glued them back together. This could be an option.

I feel that this would be outside the scope of this plugin. I understand how this particular solution would work for you, but when thinking about the general user, I can't imagine how this would be a practical behaviour.

In particular because it would mean that the writing script needs to have some way of knowing what the initial file looked like, or even that there was an original file. I don't think it's a good idea to make any assumptions about any of those when writing this as a general use tool.

So, with this as with your other script (that would read -> remove -> edit -> insert -> save, etc), I think both of those are out of the scope of a plugin whose objective is to make it possible to read HTK/HTS labels into Praat, and produce them from Praat. And in that script, you are free to add whatever warnings and caveats you wish. But I feel the plugin should be more general.

**Comment by CShulby** [comment]
ok. Would you be willing to help me integrate it with the plugin-in, maybe in a hidden folder but so that it passes all of the tests?  My old scripts work when I create the plugin my my preferences dir but it would be interesting to make them compatible with this pug-in. I would imagine that those working with TTS will find it useful.  Thinking out loud here, maybe it would be interesting to create a specific folder for this and a second setup.praat script.  We could specify this in the readme for people who desire this behaviour. maybe call it "setup_tts_specific.praat"?  What do you think about those ideas?

**Comment by jjatria** [comment]
> Would you be willing to help me integrate it with the plugin-in

Sure!

> maybe it would be interesting to create a specific folder for this and a second setup.praat script

That sounds a lot like creating a second plugin, which builds on this one. That makes perfect sense to me.

Incidentally, what exactly is it you need? To open lab files one by one and correct them? Or are you thinking of a sort of wizard that would allow you to move between labels and edit each of them? Both of these are possible.

**Comment by CShulby** [comment]
To open the lab files one by one with their corresponding audios and
manually correct the phonetic segmentation.

The trick is to edit the phoneme segmentation marks and save the context
labels which include the features for training and not to lose this
information. These labels are not necessary for segmentation. All we need
for segmentation is the center phoneme and the time stamps. But the context
labels must be preserved for training the voice.

Am 02.05.2017 10:25 vorm. schrieb "José Joaquín Atria" <
notifications@github.com>:

**Comment by jjatria** [comment]
Sure. This seems totally doable.

In its current form, are you able to work? Because I'm a bit busy with other stuff, and it might take me a bit to put together a finished version of this. If not, we can try to get something basic for now.

**Comment by CShulby** [comment]
I will try and get it to a workable form. I will work on it today and when
you are able we can finish it. Do you have an idea of when you will be able
to get your hands dirty?

Am 02.05.2017 10:39 vorm. schrieb "José Joaquín Atria" <
notifications@github.com>:

**Comment by CShulby** [comment]
This is now working in the HTS scripts.  I think that maybe it would be a good Idea to merge the hts and htk scripts and create options for the user but for now I will consider this closed
